### ISSUE TITLE
Official publish

### ISSUE THREAD

**Issue by rlogiacco** [uChip/MCP47X6#1]
Would you like to publish your library onto the [Arduino Library Manager](https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ)? 
If you are still active on this project I can submit a pull request...

**Comment by uChip** [comment]
I have no objection.

**Comment by uChip** [comment]
I have merged the PR.  Thanks.

**Comment by rlogiacco** [comment]
well, the task is not completed though...
You need to create a git tag for your library and submit an issue as steated in the guide...
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-add-my-library-to-library-manager

**Comment by uChip** [comment]
Okay.  I have not done any releases since GitHub added that feature.  I will take a look.  Thanks.

**Comment by rlogiacco** [comment]
Can I help in achieving this? 2+ years have passed since our last chat...

**Comment by uChip** [comment]
You are welcome to fork and make the change.  Unfortunately I don’t have the capability to test any changes at the moment.  Thanks.

**Comment by rlogiacco** [comment]
There are three options here, the last one of which I would rather like to avoid:

1. you create the release on this repository https://help.github.com/en/articles/creating-releases
1. you give me write permissions on this repository and I do it for you
1. I fork and create the release on my fork, but my fork will then be referenced as "the source" (and I don't want to take credit for your work)

There's anything to change and any of the options above require no more than 15 minutes of your time (actually 2 minutes once you understand how simple this is, but I understand this is your very first time at it)
