### ISSUE TITLE
max output voltage limited to 8 bit values

### ISSUE THREAD

**Issue by ederjc** [uChip/MCP47X6#3]
12 bit version MCP4726: maxium output voltage is about V_ref/4095 * 255 (0xFF) instead of V_ref/4095 * 4095 (0xFFF).
[fix_max_out_level.patch.txt](https://github.com/uChip/MCP47X6/files/1789138/fix_max_out_level.patch.txt)

**Comment by uChip** [comment]
Check to make sure you are passing the correct type.  If you pass in a uint_8t it uses 8 bits.  If you pass in a uint_16t it uses 12 bits.  The 8-bit option only works on the MCP4706.  On other parts it will behave as you describe.

**Comment by ederjc** [comment]
I tested the maximum level with:
DAC.setOutputLevel((uint16_t) 0xFFF);
and the DAC settled at about 300 mV with VCC = 5V.
Please take a look on my patch suggestion from the first comment. Thanks!

**Comment by uChip** [comment]
Yep.  Looks like I used the 3-byte format on the 4-byte write.  I will make the change.  Thanks.

**Comment by uChip** [comment]
I have made the change but do not have hardware set up to test.  Please test if you can and reopen if it's still not right.  Thanks.
